### ISSUE TITLE
`WindowsDefs.GetTickCount64` is missing

### ISSUE THREAD

**Issue by edwinyzh** [thatlr/Delphi-Tasks#1]
Hello, thanks for sharing the lib, when checking it out, i found that WindowsDefs.pas is missing from the repo. Thank!

**Comment by thatlr** [comment]
Thanks, I just updated TimeoutUtil, as I don't feel to publish another 1300 lines unit.

**Comment by edwinyzh** [comment]
I confirm it's compiable now
